apiVersion: v1
kind: Service
metadata:
  name: "go-vol-service"
  labels:
    app: go-vol-service
    system: example
spec:
  selector:
    app: "go-vol"
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: NodePort